### ISSUE TITLE
[Feature Request] Variable audio

### ISSUE THREAD

**Issue by VioletXe** [Wexop/RandomEnemiesSize#1]
I've got no clue if its possible, but could this mod also alter the audio files of affected enemies to produce longer, louder, or deeper volumes as a toggle? Heavier thumps and throatier roars from thumpers would be pretty cool.

**Comment by Wexop** [comment]
Hey !
This was already requested by someone, im working on it :)

**Comment by Wexop** [comment]
This feature is in the v1.1.3 of the mode :)
