### ISSUE TITLE
Wishlist - Changelog

### ISSUE THREAD

**Issue by NeatWolf** [Wexop/RandomEnemiesSize#3]
Hi! 

Is there any chance you could share a changelog somewhere in the thunderstore (there should be an appropriate section)? 

It would really help people when deciding when to upgrade, or to decide if the config file needs to be regenerated to share it with friends ^^

I love keeping all mods up to date but it kinda becomes a responsibility when other people depend on you to make sure the modpack is always in a working playable state - so getting to know what's happening under the hood would be immensely appreciated ^^

**Comment by Wexop** [comment]
Hey, thanks for the report !

I totaly understand that, i'll try to add that in the next patch ! 

If you got any questions about the actual state of the feel free to ask :)

**Comment by Wexop** [comment]
I just added a changelog that you can read on thunderstore :)
