### ISSUE TITLE
random chance option

### ISSUE THREAD

**Issue by quiloulou** [Wexop/RandomEnemiesSize#5]
hi i love the idea of the mod, can we have a option for chance of size changing.? per exemple i want 1% chance to monster to have a random size to make it rare like a shiny in pokemon.

**Comment by Wexop** [comment]
Hey !
I like this idea, im going to working on it rn :)

**Comment by Wexop** [comment]
It's done ! You can find the ChanceOfRandomSize config in the v1.1.6 :)
Have fun and thanks for the idea

**Comment by quiloulou** [comment]
wow so fast thanks a lot <3
